### ISSUE TITLE
Possible error on micro enterprise taxation calculation

### ISSUE THREAD

**Issue by benneynens** [marilius12/taxes#2]
In regards to [this calculation](https://taxes.pages.dev/example-calculations#micro-enterprise-in-romania-), I think there is an error on the calculation on the effective tax.

The employee salary of 2300, which results in a tax of 914, is *monthly*.

The total tax calculation is currently as follows: RON 26,783.31 = 51.75 + 3,933.64 + 914 + 21,883.92

I believe it should be: 51.75 + 3,933.64 + (12 * 914 ) + 21,883.92

Apologies if its my error.

**Comment by marilius12** [comment]
Great point; should be fixed in 4a09553. Thanks for bringing this up!
